# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Clinostat.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../_image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image_Frame = QtWidgets.QLabel(self.centralwidget)
        self.Image_Frame.setGeometry(QtCore.QRect(659, 10, 350, 350))
        self.Image_Frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.Image_Frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Image_Frame.setLineWidth(3)
        self.Image_Frame.setText("")
        self.Image_Frame.setPixmap(QtGui.QPixmap("../_image/Background.png"))
        self.Image_Frame.setScaledContents(True)
        self.Image_Frame.setObjectName("Image_Frame")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 631, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.Lighting_tab = QtWidgets.QWidget()
        self.Lighting_tab.setObjectName("Lighting_tab")
        self.frame = QtWidgets.QFrame(self.Lighting_tab)
        self.frame.setGeometry(QtCore.QRect(0, 20, 411, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.coreImage = QtWidgets.QLabel(self.frame)
        self.coreImage.setGeometry(QtCore.QRect(55, 0, 300, 300))
        self.coreImage.setText("")
        self.coreImage.setPixmap(QtGui.QPixmap("../_image/Core.png"))
        self.coreImage.setScaledContents(True)
        self.coreImage.setObjectName("coreImage")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(20, 320, 361, 171))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.Address_label = QtWidgets.QLabel(self.frame_5)
        self.Address_label.setGeometry(QtCore.QRect(110, 0, 141, 31))
        self.Address_label.setObjectName("Address_label")
        self.color_label = QtWidgets.QLabel(self.frame_5)
        self.color_label.setGeometry(QtCore.QRect(110, 65, 141, 31))
        self.color_label.setObjectName("color_label")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.frame_5)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 19, 321, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.Start_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.Start_label.setObjectName("Start_label")
        self.verticalLayout_14.addWidget(self.Start_label)
        self.Start_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.Start_spinBox.setMaximum(33)
        self.Start_spinBox.setObjectName("Start_spinBox")
        self.verticalLayout_14.addWidget(self.Start_spinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.Start_label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.Start_label_3.setObjectName("Start_label_3")
        self.verticalLayout_15.addWidget(self.Start_label_3)
        self.End_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.End_spinBox.setMinimum(1)
        self.End_spinBox.setMaximum(34)
        self.End_spinBox.setObjectName("End_spinBox")
        self.verticalLayout_15.addWidget(self.End_spinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.BRT_lable = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.BRT_lable.setObjectName("BRT_lable")
        self.verticalLayout_16.addWidget(self.BRT_lable)
        self.BRT_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.BRT_spinBox.setMinimum(1)
        self.BRT_spinBox.setMaximum(255)
        self.BRT_spinBox.setProperty("value", 50)
        self.BRT_spinBox.setObjectName("BRT_spinBox")
        self.verticalLayout_16.addWidget(self.BRT_spinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_16)
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_5)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 331, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.B_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B_spinBox.setMaximum(255)
        self.B_spinBox.setObjectName("B_spinBox")
        self.gridLayout.addWidget(self.B_spinBox, 1, 1, 1, 1)
        self.W_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.W_label.setObjectName("W_label")
        self.gridLayout.addWidget(self.W_label, 1, 2, 1, 1)
        self.R_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.R_spinBox.setMaximum(255)
        self.R_spinBox.setObjectName("R_spinBox")
        self.gridLayout.addWidget(self.R_spinBox, 0, 1, 1, 1)
        self.W_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.W_spinBox.setMaximum(255)
        self.W_spinBox.setObjectName("W_spinBox")
        self.gridLayout.addWidget(self.W_spinBox, 1, 3, 1, 1)
        self.G_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.G_spinBox.setMaximum(255)
        self.G_spinBox.setObjectName("G_spinBox")
        self.gridLayout.addWidget(self.G_spinBox, 0, 3, 1, 1)
        self.light_Reset_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.light_Reset_pushButton.setObjectName("light_Reset_pushButton")
        self.gridLayout.addWidget(self.light_Reset_pushButton, 0, 4, 1, 1)
        self.light_Confirm_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.light_Confirm_pushButton.setObjectName("light_Confirm_pushButton")
        self.gridLayout.addWidget(self.light_Confirm_pushButton, 1, 4, 1, 1)
        self.G_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.G_label.setObjectName("G_label")
        self.gridLayout.addWidget(self.G_label, 0, 2, 1, 1)
        self.R_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.R_label.setObjectName("R_label")
        self.gridLayout.addWidget(self.R_label, 0, 0, 1, 1)
        self.B_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.B_label.setObjectName("B_label")
        self.gridLayout.addWidget(self.B_label, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.Lighting_tab)
        self.frame_2.setGeometry(QtCore.QRect(420, 20, 191, 381))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.presets_label = QtWidgets.QLabel(self.frame_2)
        self.presets_label.setGeometry(QtCore.QRect(30, 20, 141, 31))
        self.presets_label.setObjectName("presets_label")
        self.rainbow_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.rainbow_pushButton.setEnabled(False)
        self.rainbow_pushButton.setGeometry(QtCore.QRect(40, 60, 121, 41))
        self.rainbow_pushButton.setObjectName("rainbow_pushButton")
        self.disco_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.disco_pushButton.setEnabled(False)
        self.disco_pushButton.setGeometry(QtCore.QRect(40, 120, 121, 41))
        self.disco_pushButton.setObjectName("disco_pushButton")
        self.lightCycle_label = QtWidgets.QLabel(self.frame_2)
        self.lightCycle_label.setGeometry(QtCore.QRect(30, 210, 141, 31))
        self.lightCycle_label.setObjectName("lightCycle_label")
        self.powerCycle_spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.powerCycle_spinBox.setGeometry(QtCore.QRect(40, 270, 121, 22))
        self.powerCycle_spinBox.setMinimum(1)
        self.powerCycle_spinBox.setMaximum(999999999)
        self.powerCycle_spinBox.setProperty("value", 60)
        self.powerCycle_spinBox.setObjectName("powerCycle_spinBox")
        self.Cycle_label = QtWidgets.QLabel(self.frame_2)
        self.Cycle_label.setGeometry(QtCore.QRect(50, 240, 121, 31))
        self.Cycle_label.setObjectName("Cycle_label")
        self.confirmCycle_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.confirmCycle_pushButton.setGeometry(QtCore.QRect(40, 310, 121, 31))
        self.confirmCycle_pushButton.setObjectName("confirmCycle_pushButton")
        self.IR_pushButton = QtWidgets.QPushButton(self.Lighting_tab)
        self.IR_pushButton.setGeometry(QtCore.QRect(450, 440, 141, 51))
        self.IR_pushButton.setObjectName("IR_pushButton")
        self.IR_checkBox = QtWidgets.QCheckBox(self.Lighting_tab)
        self.IR_checkBox.setGeometry(QtCore.QRect(450, 496, 141, 21))
        self.IR_checkBox.setObjectName("IR_checkBox")
        self.tabWidget.addTab(self.Lighting_tab, "")
        self.Frame_tab = QtWidgets.QWidget()
        self.Frame_tab.setObjectName("Frame_tab")
        self.frameReverse_pushButton = QtWidgets.QPushButton(self.Frame_tab)
        self.frameReverse_pushButton.setGeometry(QtCore.QRect(80, 370, 41, 41))
        self.frameReverse_pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../_image/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.frameReverse_pushButton.setIcon(icon1)
        self.frameReverse_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.frameReverse_pushButton.setObjectName("frameReverse_pushButton")
        self.link_pushButton = QtWidgets.QPushButton(self.Frame_tab)
        self.link_pushButton.setGeometry(QtCore.QRect(280, 180, 50, 50))
        self.link_pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../_image/Link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.link_pushButton.setIcon(icon2)
        self.link_pushButton.setIconSize(QtCore.QSize(30, 30))
        self.link_pushButton.setCheckable(False)
        self.link_pushButton.setObjectName("link_pushButton")
        self.coreReverse_pushButton = QtWidgets.QPushButton(self.Frame_tab)
        self.coreReverse_pushButton.setGeometry(QtCore.QRect(490, 370, 41, 41))
        self.coreReverse_pushButton.setText("")
        self.coreReverse_pushButton.setIcon(icon1)
        self.coreReverse_pushButton.setIconSize(QtCore.QSize(20, 20))
        self.coreReverse_pushButton.setObjectName("coreReverse_pushButton")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.Frame_tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(130, 10, 51, 401))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.frame_label.setObjectName("frame_label")
        self.verticalLayout_20.addWidget(self.frame_label)
        self.frame_verticalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_6)
        self.frame_verticalSlider.setMinimum(3)
        self.frame_verticalSlider.setMaximum(150)
        self.frame_verticalSlider.setTracking(True)
        self.frame_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.frame_verticalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.frame_verticalSlider.setTickInterval(5)
        self.frame_verticalSlider.setObjectName("frame_verticalSlider")
        self.verticalLayout_20.addWidget(self.frame_verticalSlider, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.Frame_tab)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(430, 10, 51, 401))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.core_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.core_label.setObjectName("core_label")
        self.verticalLayout_22.addWidget(self.core_label)
        self.core_verticalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_8)
        self.core_verticalSlider.setMinimum(3)
        self.core_verticalSlider.setMaximum(150)
        self.core_verticalSlider.setTracking(True)
        self.core_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.core_verticalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.core_verticalSlider.setTickInterval(5)
        self.core_verticalSlider.setObjectName("core_verticalSlider")
        self.verticalLayout_22.addWidget(self.core_verticalSlider, 0, QtCore.Qt.AlignHCenter)
        self.frameErgz_pushButton = QtWidgets.QPushButton(self.Frame_tab)
        self.frameErgz_pushButton.setGeometry(QtCore.QRect(80, 462, 149, 41))
        self.frameErgz_pushButton.setObjectName("frameErgz_pushButton")
        self.frame_spinBox = QtWidgets.QDoubleSpinBox(self.Frame_tab)
        self.frame_spinBox.setGeometry(QtCore.QRect(80, 419, 149, 31))
        self.frame_spinBox.setDecimals(1)
        self.frame_spinBox.setMinimum(0.3)
        self.frame_spinBox.setMaximum(15.0)
        self.frame_spinBox.setSingleStep(0.1)
        self.frame_spinBox.setObjectName("frame_spinBox")
        self.core_spinBox = QtWidgets.QDoubleSpinBox(self.Frame_tab)
        self.core_spinBox.setGeometry(QtCore.QRect(380, 419, 149, 31))
        self.core_spinBox.setDecimals(1)
        self.core_spinBox.setMinimum(0.3)
        self.core_spinBox.setMaximum(15.0)
        self.core_spinBox.setSingleStep(0.1)
        self.core_spinBox.setObjectName("core_spinBox")
        self.coreErgz_pushButton = QtWidgets.QPushButton(self.Frame_tab)
        self.coreErgz_pushButton.setGeometry(QtCore.QRect(380, 462, 149, 41))
        self.coreErgz_pushButton.setObjectName("coreErgz_pushButton")
        self.tabWidget.addTab(self.Frame_tab, "")
        self.Imaging_tab = QtWidgets.QWidget()
        self.Imaging_tab.setObjectName("Imaging_tab")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Imaging_tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 40, 611, 311))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Image_Title = QtWidgets.QLabel(self.layoutWidget_2)
        self.Image_Title.setObjectName("Image_Title")
        self.verticalLayout.addWidget(self.Image_Title)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.title_lineEdit.setEnabled(True)
        self.title_lineEdit.setObjectName("title_lineEdit")
        self.horizontalLayout_2.addWidget(self.title_lineEdit)
        self.addDate_pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.addDate_pushButton.setEnabled(False)
        self.addDate_pushButton.setObjectName("addDate_pushButton")
        self.horizontalLayout_2.addWidget(self.addDate_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Image_Interval = QtWidgets.QLabel(self.layoutWidget_2)
        self.Image_Interval.setObjectName("Image_Interval")
        self.verticalLayout.addWidget(self.Image_Interval)
        self.ICI_spinBox = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.ICI_spinBox.setEnabled(True)
        self.ICI_spinBox.setMinimum(1)
        self.ICI_spinBox.setMaximum(99999999)
        self.ICI_spinBox.setObjectName("ICI_spinBox")
        self.verticalLayout.addWidget(self.ICI_spinBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Image_Duration = QtWidgets.QLabel(self.layoutWidget_2)
        self.Image_Duration.setObjectName("Image_Duration")
        self.verticalLayout_2.addWidget(self.Image_Duration)
        self.ISD_spinBox = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.ISD_spinBox.setEnabled(True)
        self.ISD_spinBox.setMinimum(1)
        self.ISD_spinBox.setMaximum(99999999)
        self.ISD_spinBox.setObjectName("ISD_spinBox")
        self.verticalLayout_2.addWidget(self.ISD_spinBox)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.directory_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.directory_label.setEnabled(True)
        self.directory_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.directory_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.directory_label.setAlignment(QtCore.Qt.AlignCenter)
        self.directory_label.setObjectName("directory_label")
        self.verticalLayout_2.addWidget(self.directory_label)
        self.directory_pushButton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.directory_pushButton.setEnabled(True)
        self.directory_pushButton.setCheckable(False)
        self.directory_pushButton.setObjectName("directory_pushButton")
        self.verticalLayout_2.addWidget(self.directory_pushButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.layoutWidget = QtWidgets.QWidget(self.Imaging_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 440, 611, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Progress_Label = QtWidgets.QLabel(self.layoutWidget)
        self.Progress_Label.setObjectName("Progress_Label")
        self.verticalLayout_6.addWidget(self.Progress_Label, 0, QtCore.Qt.AlignHCenter)
        self.Progress_Bar = QtWidgets.QProgressBar(self.layoutWidget)
        self.Progress_Bar.setEnabled(False)
        self.Progress_Bar.setProperty("value", 0)
        self.Progress_Bar.setObjectName("Progress_Bar")
        self.verticalLayout_6.addWidget(self.Progress_Bar)
        self.resolution_label = QtWidgets.QLabel(self.Imaging_tab)
        self.resolution_label.setGeometry(QtCore.QRect(45, 360, 231, 31))
        self.resolution_label.setObjectName("resolution_label")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.Imaging_tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(420, 380, 201, 61))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.JPG_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.JPG_radioButton.setChecked(True)
        self.JPG_radioButton.setObjectName("JPG_radioButton")
        self.horizontalLayout_7.addWidget(self.JPG_radioButton)
        self.PNG_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.PNG_radioButton.setObjectName("PNG_radioButton")
        self.horizontalLayout_7.addWidget(self.PNG_radioButton)
        self.resolution_label_2 = QtWidgets.QLabel(self.Imaging_tab)
        self.resolution_label_2.setGeometry(QtCore.QRect(390, 360, 231, 31))
        self.resolution_label_2.setObjectName("resolution_label_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.Imaging_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 390, 281, 54))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CoreCtr_label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.CoreCtr_label_5.setObjectName("CoreCtr_label_5")
        self.gridLayout_2.addWidget(self.CoreCtr_label_5, 0, 1, 1, 1)
        self.x_resolution_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.x_resolution_spinBox.setMinimum(50)
        self.x_resolution_spinBox.setMaximum(3240)
        self.x_resolution_spinBox.setProperty("value", 2464)
        self.x_resolution_spinBox.setObjectName("x_resolution_spinBox")
        self.gridLayout_2.addWidget(self.x_resolution_spinBox, 0, 0, 1, 1)
        self.y_resolution_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.y_resolution_spinBox.setMinimum(50)
        self.y_resolution_spinBox.setMaximum(2464)
        self.y_resolution_spinBox.setProperty("value", 2464)
        self.y_resolution_spinBox.setObjectName("y_resolution_spinBox")
        self.gridLayout_2.addWidget(self.y_resolution_spinBox, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.CoreCtr_label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.CoreCtr_label_6.setObjectName("CoreCtr_label_6")
        self.gridLayout_2.addWidget(self.CoreCtr_label_6, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 2, 1, 1)
        self.tabWidget.addTab(self.Imaging_tab, "")
        self.core_tab = QtWidgets.QWidget()
        self.core_tab.setObjectName("core_tab")
        self.frame_6 = QtWidgets.QFrame(self.core_tab)
        self.frame_6.setEnabled(True)
        self.frame_6.setGeometry(QtCore.QRect(360, 10, 261, 411))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.Expert_tab = QtWidgets.QTabWidget(self.frame_6)
        self.Expert_tab.setGeometry(QtCore.QRect(20, 10, 231, 381))
        self.Expert_tab.setObjectName("Expert_tab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 201, 331))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frameCD_spinBox = QtWidgets.QSpinBox(self.frame_3)
        self.frameCD_spinBox.setGeometry(QtCore.QRect(40, 50, 121, 22))
        self.frameCD_spinBox.setPrefix("")
        self.frameCD_spinBox.setMinimum(-200)
        self.frameCD_spinBox.setMaximum(200)
        self.frameCD_spinBox.setObjectName("frameCD_spinBox")
        self.frameCD_label = QtWidgets.QLabel(self.frame_3)
        self.frameCD_label.setGeometry(QtCore.QRect(40, 30, 121, 21))
        self.frameCD_label.setObjectName("frameCD_label")
        self.framePW_spinBox = QtWidgets.QSpinBox(self.frame_3)
        self.framePW_spinBox.setGeometry(QtCore.QRect(40, 100, 121, 22))
        self.framePW_spinBox.setPrefix("")
        self.framePW_spinBox.setMinimum(1)
        self.framePW_spinBox.setMaximum(1000)
        self.framePW_spinBox.setProperty("value", 2)
        self.framePW_spinBox.setObjectName("framePW_spinBox")
        self.framePI_spinBox = QtWidgets.QSpinBox(self.frame_3)
        self.framePI_spinBox.setGeometry(QtCore.QRect(40, 150, 121, 22))
        self.framePI_spinBox.setMinimum(1)
        self.framePI_spinBox.setMaximum(10000000)
        self.framePI_spinBox.setProperty("value", 380)
        self.framePI_spinBox.setObjectName("framePI_spinBox")
        self.framePW_label = QtWidgets.QLabel(self.frame_3)
        self.framePW_label.setGeometry(QtCore.QRect(40, 80, 121, 21))
        self.framePW_label.setObjectName("framePW_label")
        self.framePI_label = QtWidgets.QLabel(self.frame_3)
        self.framePI_label.setGeometry(QtCore.QRect(40, 130, 121, 21))
        self.framePI_label.setObjectName("framePI_label")
        self.frameEC_label = QtWidgets.QLabel(self.frame_3)
        self.frameEC_label.setGeometry(QtCore.QRect(40, 10, 121, 21))
        self.frameEC_label.setObjectName("frameEC_label")
        self.frameMS_label = QtWidgets.QLabel(self.frame_3)
        self.frameMS_label.setGeometry(QtCore.QRect(40, 180, 121, 21))
        self.frameMS_label.setObjectName("frameMS_label")
        self.frameApply_pushButton = QtWidgets.QPushButton(self.frame_3)
        self.frameApply_pushButton.setGeometry(QtCore.QRect(30, 280, 141, 21))
        self.frameApply_pushButton.setObjectName("frameApply_pushButton")
        self.frameMS_comboBox = QtWidgets.QComboBox(self.frame_3)
        self.frameMS_comboBox.setGeometry(QtCore.QRect(40, 200, 121, 22))
        self.frameMS_comboBox.setObjectName("frameMS_comboBox")
        self.frameMS_comboBox.addItem("")
        self.frameMS_comboBox.addItem("")
        self.frameMS_comboBox.addItem("")
        self.frameMS_comboBox.addItem("")
        self.frameMS_comboBox.addItem("")
        self.frameMS_comboBox.addItem("")
        self.frameMS_comboBox.addItem("")
        self.frameMS_comboBox.addItem("")
        self.frameReset_pushButton = QtWidgets.QPushButton(self.frame_3)
        self.frameReset_pushButton.setGeometry(QtCore.QRect(30, 250, 141, 21))
        self.frameReset_pushButton.setObjectName("frameReset_pushButton")
        self.Expert_tab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 201, 331))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.coreCD_spinBox = QtWidgets.QSpinBox(self.frame_4)
        self.coreCD_spinBox.setGeometry(QtCore.QRect(40, 50, 121, 22))
        self.coreCD_spinBox.setPrefix("")
        self.coreCD_spinBox.setMinimum(-200)
        self.coreCD_spinBox.setMaximum(200)
        self.coreCD_spinBox.setObjectName("coreCD_spinBox")
        self.coreCD_label = QtWidgets.QLabel(self.frame_4)
        self.coreCD_label.setGeometry(QtCore.QRect(40, 30, 121, 21))
        self.coreCD_label.setObjectName("coreCD_label")
        self.corePW_spinBox = QtWidgets.QSpinBox(self.frame_4)
        self.corePW_spinBox.setGeometry(QtCore.QRect(40, 100, 121, 22))
        self.corePW_spinBox.setPrefix("")
        self.corePW_spinBox.setMinimum(1)
        self.corePW_spinBox.setMaximum(1000)
        self.corePW_spinBox.setProperty("value", 2)
        self.corePW_spinBox.setObjectName("corePW_spinBox")
        self.corePI_spinBox = QtWidgets.QSpinBox(self.frame_4)
        self.corePI_spinBox.setGeometry(QtCore.QRect(40, 150, 121, 22))
        self.corePI_spinBox.setMinimum(1)
        self.corePI_spinBox.setMaximum(10000000)
        self.corePI_spinBox.setProperty("value", 380)
        self.corePI_spinBox.setObjectName("corePI_spinBox")
        self.corePW_label = QtWidgets.QLabel(self.frame_4)
        self.corePW_label.setGeometry(QtCore.QRect(40, 80, 121, 21))
        self.corePW_label.setObjectName("corePW_label")
        self.corePI_label = QtWidgets.QLabel(self.frame_4)
        self.corePI_label.setGeometry(QtCore.QRect(40, 130, 121, 21))
        self.corePI_label.setObjectName("corePI_label")
        self.coreEC_label = QtWidgets.QLabel(self.frame_4)
        self.coreEC_label.setGeometry(QtCore.QRect(40, 10, 121, 21))
        self.coreEC_label.setObjectName("coreEC_label")
        self.coreMS_label = QtWidgets.QLabel(self.frame_4)
        self.coreMS_label.setGeometry(QtCore.QRect(40, 180, 121, 21))
        self.coreMS_label.setObjectName("coreMS_label")
        self.coreApply_pushButton = QtWidgets.QPushButton(self.frame_4)
        self.coreApply_pushButton.setGeometry(QtCore.QRect(30, 280, 141, 21))
        self.coreApply_pushButton.setObjectName("coreApply_pushButton")
        self.coreMS_comboBox = QtWidgets.QComboBox(self.frame_4)
        self.coreMS_comboBox.setGeometry(QtCore.QRect(40, 200, 121, 22))
        self.coreMS_comboBox.setObjectName("coreMS_comboBox")
        self.coreMS_comboBox.addItem("")
        self.coreMS_comboBox.addItem("")
        self.coreMS_comboBox.addItem("")
        self.coreMS_comboBox.addItem("")
        self.coreMS_comboBox.addItem("")
        self.coreMS_comboBox.addItem("")
        self.coreMS_comboBox.addItem("")
        self.coreMS_comboBox.addItem("")
        self.frameReset_pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.frameReset_pushButton_2.setGeometry(QtCore.QRect(30, 250, 141, 21))
        self.frameReset_pushButton_2.setObjectName("frameReset_pushButton_2")
        self.Expert_tab.addTab(self.tab_2, "")
        self.frame_7 = QtWidgets.QFrame(self.core_tab)
        self.frame_7.setGeometry(QtCore.QRect(10, 20, 331, 111))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.frame_7)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 311, 61))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frameCI_lineEdit_1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.frameCI_lineEdit_1.setObjectName("frameCI_lineEdit_1")
        self.horizontalLayout_6.addWidget(self.frameCI_lineEdit_1)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.frameCI_lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.frameCI_lineEdit_2.setObjectName("frameCI_lineEdit_2")
        self.horizontalLayout_6.addWidget(self.frameCI_lineEdit_2)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.frameCI_lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.frameCI_lineEdit_3.setObjectName("frameCI_lineEdit_3")
        self.horizontalLayout_6.addWidget(self.frameCI_lineEdit_3)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.label_5)
        self.frameCI_lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.frameCI_lineEdit_4.setObjectName("frameCI_lineEdit_4")
        self.horizontalLayout_6.addWidget(self.frameCI_lineEdit_4)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.frameCI_lineEdit_5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.frameCI_lineEdit_5.setObjectName("frameCI_lineEdit_5")
        self.horizontalLayout_6.addWidget(self.frameCI_lineEdit_5)
        self.frameCI_label = QtWidgets.QLabel(self.frame_7)
        self.frameCI_label.setGeometry(QtCore.QRect(80, 10, 171, 21))
        self.frameCI_label.setObjectName("frameCI_label")
        self.frameCI_pushButton = QtWidgets.QPushButton(self.frame_7)
        self.frameCI_pushButton.setGeometry(QtCore.QRect(180, 80, 141, 21))
        self.frameCI_pushButton.setObjectName("frameCI_pushButton")
        self.frame_15 = QtWidgets.QFrame(self.core_tab)
        self.frame_15.setGeometry(QtCore.QRect(10, 150, 331, 111))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.frame_15)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 20, 311, 61))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.coreCI_lineEdit_1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.coreCI_lineEdit_1.setObjectName("coreCI_lineEdit_1")
        self.horizontalLayout_12.addWidget(self.coreCI_lineEdit_1)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.coreCI_lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.coreCI_lineEdit_2.setObjectName("coreCI_lineEdit_2")
        self.horizontalLayout_12.addWidget(self.coreCI_lineEdit_2)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.coreCI_lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.coreCI_lineEdit_3.setObjectName("coreCI_lineEdit_3")
        self.horizontalLayout_12.addWidget(self.coreCI_lineEdit_3)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.coreCI_lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.coreCI_lineEdit_4.setObjectName("coreCI_lineEdit_4")
        self.horizontalLayout_12.addWidget(self.coreCI_lineEdit_4)
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.coreCI_lineEdit_5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_10)
        self.coreCI_lineEdit_5.setObjectName("coreCI_lineEdit_5")
        self.horizontalLayout_12.addWidget(self.coreCI_lineEdit_5)
        self.coreCI_label = QtWidgets.QLabel(self.frame_15)
        self.coreCI_label.setGeometry(QtCore.QRect(80, 10, 171, 21))
        self.coreCI_label.setObjectName("coreCI_label")
        self.coreCI_pushButton = QtWidgets.QPushButton(self.frame_15)
        self.coreCI_pushButton.setGeometry(QtCore.QRect(180, 80, 141, 21))
        self.coreCI_pushButton.setObjectName("coreCI_pushButton")
        self.frame_16 = QtWidgets.QFrame(self.core_tab)
        self.frame_16.setGeometry(QtCore.QRect(10, 280, 331, 111))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.frame_16)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(10, 20, 311, 61))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.lightingCI_lineEdit_1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.lightingCI_lineEdit_1.setObjectName("lightingCI_lineEdit_1")
        self.horizontalLayout_13.addWidget(self.lightingCI_lineEdit_1)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_13.addWidget(self.label_17)
        self.lightingCI_lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.lightingCI_lineEdit_2.setObjectName("lightingCI_lineEdit_2")
        self.horizontalLayout_13.addWidget(self.lightingCI_lineEdit_2)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.lightingCI_lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.lightingCI_lineEdit_3.setObjectName("lightingCI_lineEdit_3")
        self.horizontalLayout_13.addWidget(self.lightingCI_lineEdit_3)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_13.addWidget(self.label_19)
        self.lightingCI_lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.lightingCI_lineEdit_4.setObjectName("lightingCI_lineEdit_4")
        self.horizontalLayout_13.addWidget(self.lightingCI_lineEdit_4)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_13.addWidget(self.label_20)
        self.lightingCI_lineEdit_5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.lightingCI_lineEdit_5.setObjectName("lightingCI_lineEdit_5")
        self.horizontalLayout_13.addWidget(self.lightingCI_lineEdit_5)
        self.lightingCI_label = QtWidgets.QLabel(self.frame_16)
        self.lightingCI_label.setGeometry(QtCore.QRect(80, 10, 171, 21))
        self.lightingCI_label.setObjectName("lightingCI_label")
        self.lightingCI_pushButton = QtWidgets.QPushButton(self.frame_16)
        self.lightingCI_pushButton.setGeometry(QtCore.QRect(180, 80, 141, 21))
        self.lightingCI_pushButton.setObjectName("lightingCI_pushButton")
        self.frame_17 = QtWidgets.QFrame(self.core_tab)
        self.frame_17.setGeometry(QtCore.QRect(10, 410, 331, 111))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.frame_17)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(10, 20, 311, 61))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.ImagingCI_lineEdit_1 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.ImagingCI_lineEdit_1.setObjectName("ImagingCI_lineEdit_1")
        self.horizontalLayout_14.addWidget(self.ImagingCI_lineEdit_1)
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_14.addWidget(self.label_21)
        self.ImagingCI_lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.ImagingCI_lineEdit_2.setObjectName("ImagingCI_lineEdit_2")
        self.horizontalLayout_14.addWidget(self.ImagingCI_lineEdit_2)
        self.label_22 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_14.addWidget(self.label_22)
        self.ImagingCI_lineEdit_3 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.ImagingCI_lineEdit_3.setObjectName("ImagingCI_lineEdit_3")
        self.horizontalLayout_14.addWidget(self.ImagingCI_lineEdit_3)
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_14.addWidget(self.label_23)
        self.ImagingCI_lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.ImagingCI_lineEdit_4.setObjectName("ImagingCI_lineEdit_4")
        self.horizontalLayout_14.addWidget(self.ImagingCI_lineEdit_4)
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_14.addWidget(self.label_24)
        self.ImagingCI_lineEdit_5 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_12)
        self.ImagingCI_lineEdit_5.setObjectName("ImagingCI_lineEdit_5")
        self.horizontalLayout_14.addWidget(self.ImagingCI_lineEdit_5)
        self.imagingCI_label = QtWidgets.QLabel(self.frame_17)
        self.imagingCI_label.setGeometry(QtCore.QRect(80, 10, 171, 21))
        self.imagingCI_label.setObjectName("imagingCI_label")
        self.imagingCI_pushButton = QtWidgets.QPushButton(self.frame_17)
        self.imagingCI_pushButton.setGeometry(QtCore.QRect(180, 80, 141, 21))
        self.imagingCI_pushButton.setObjectName("imagingCI_pushButton")
        self.tabWidget.addTab(self.core_tab, "")
        self.startImaging_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.startImaging_pushButton.setEnabled(False)
        self.startImaging_pushButton.setGeometry(QtCore.QRect(830, 490, 181, 61))
        self.startImaging_pushButton.setObjectName("startImaging_pushButton")
        self.snapshot_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.snapshot_pushButton.setEnabled(True)
        self.snapshot_pushButton.setGeometry(QtCore.QRect(868, 370, 141, 21))
        self.snapshot_pushButton.setObjectName("snapshot_pushButton")
        self.preview_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.preview_pushButton.setEnabled(True)
        self.preview_pushButton.setGeometry(QtCore.QRect(868, 400, 141, 21))
        self.preview_pushButton.setObjectName("preview_pushButton")
        self.version_label = QtWidgets.QLabel(self.centralwidget)
        self.version_label.setGeometry(QtCore.QRect(670, 550, 141, 20))
        self.version_label.setObjectName("version_label")
        self.Sensor_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.Sensor_tabWidget.setGeometry(QtCore.QRect(660, 390, 161, 161))
        self.Sensor_tabWidget.setObjectName("Sensor_tabWidget")
        self.ACC_tab = QtWidgets.QWidget()
        self.ACC_tab.setObjectName("ACC_tab")
        self.ACC_label = QtWidgets.QLabel(self.ACC_tab)
        self.ACC_label.setGeometry(QtCore.QRect(10, 0, 141, 31))
        self.ACC_label.setObjectName("ACC_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.ACC_tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 151, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ACC_X_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_X_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_X_label.setObjectName("ACC_X_label")
        self.verticalLayout_4.addWidget(self.ACC_X_label)
        self.ACC_Y_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_Y_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_Y_label.setObjectName("ACC_Y_label")
        self.verticalLayout_4.addWidget(self.ACC_Y_label)
        self.ACC_Z_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_Z_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_Z_label.setObjectName("ACC_Z_label")
        self.verticalLayout_4.addWidget(self.ACC_Z_label)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.ACC_X_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_X_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_X_text_label.setObjectName("ACC_X_text_label")
        self.verticalLayout_5.addWidget(self.ACC_X_text_label)
        self.ACC_Y_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_Y_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_Y_text_label.setObjectName("ACC_Y_text_label")
        self.verticalLayout_5.addWidget(self.ACC_Y_text_label)
        self.ACC_Z_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_Z_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_Z_text_label.setObjectName("ACC_Z_text_label")
        self.verticalLayout_5.addWidget(self.ACC_Z_text_label)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.ACC_X_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_X_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_X_Unit_label.setObjectName("ACC_X_Unit_label")
        self.verticalLayout_7.addWidget(self.ACC_X_Unit_label)
        self.ACC_Y_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_Y_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_Y_Unit_label.setObjectName("ACC_Y_Unit_label")
        self.verticalLayout_7.addWidget(self.ACC_Y_Unit_label)
        self.ACC_Z_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.ACC_Z_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.ACC_Z_Unit_label.setObjectName("ACC_Z_Unit_label")
        self.verticalLayout_7.addWidget(self.ACC_Z_Unit_label)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.Sensor_tabWidget.addTab(self.ACC_tab, "")
        self.GYRO_tab = QtWidgets.QWidget()
        self.GYRO_tab.setObjectName("GYRO_tab")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.GYRO_tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 30, 151, 91))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.GYRO_X_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.GYRO_X_label.setAlignment(QtCore.Qt.AlignCenter)
        self.GYRO_X_label.setObjectName("GYRO_X_label")
        self.verticalLayout_8.addWidget(self.GYRO_X_label)
        self.GYRO_Y_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.GYRO_Y_label.setAlignment(QtCore.Qt.AlignCenter)
        self.GYRO_Y_label.setObjectName("GYRO_Y_label")
        self.verticalLayout_8.addWidget(self.GYRO_Y_label)
        self.GYRO_Z_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.GYRO_Z_label.setAlignment(QtCore.Qt.AlignCenter)
        self.GYRO_Z_label.setObjectName("GYRO_Z_label")
        self.verticalLayout_8.addWidget(self.GYRO_Z_label)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.GYRO_X_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.GYRO_X_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.GYRO_X_text_label.setObjectName("GYRO_X_text_label")
        self.verticalLayout_9.addWidget(self.GYRO_X_text_label)
        self.GYRO_Y_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.GYRO_Y_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.GYRO_Y_text_label.setObjectName("GYRO_Y_text_label")
        self.verticalLayout_9.addWidget(self.GYRO_Y_text_label)
        self.GYRO_Z_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.GYRO_Z_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.GYRO_Z_text_label.setObjectName("GYRO_Z_text_label")
        self.verticalLayout_9.addWidget(self.GYRO_Z_text_label)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.GYRO_X_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.GYRO_X_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.GYRO_X_Unit_label.setObjectName("GYRO_X_Unit_label")
        self.verticalLayout_10.addWidget(self.GYRO_X_Unit_label)
        self.GYRO_Y_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.GYRO_Y_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.GYRO_Y_Unit_label.setObjectName("GYRO_Y_Unit_label")
        self.verticalLayout_10.addWidget(self.GYRO_Y_Unit_label)
        self.GYRO_Z_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.GYRO_Z_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.GYRO_Z_Unit_label.setObjectName("GYRO_Z_Unit_label")
        self.verticalLayout_10.addWidget(self.GYRO_Z_Unit_label)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.GYRO_label = QtWidgets.QLabel(self.GYRO_tab)
        self.GYRO_label.setGeometry(QtCore.QRect(10, 0, 141, 31))
        self.GYRO_label.setObjectName("GYRO_label")
        self.Sensor_tabWidget.addTab(self.GYRO_tab, "")
        self.MAG_tab = QtWidgets.QWidget()
        self.MAG_tab.setObjectName("MAG_tab")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.MAG_tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 30, 151, 91))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.MAG_X_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.MAG_X_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MAG_X_label.setObjectName("MAG_X_label")
        self.verticalLayout_11.addWidget(self.MAG_X_label)
        self.MAG_Y_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.MAG_Y_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MAG_Y_label.setObjectName("MAG_Y_label")
        self.verticalLayout_11.addWidget(self.MAG_Y_label)
        self.MAG_Z_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.MAG_Z_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MAG_Z_label.setObjectName("MAG_Z_label")
        self.verticalLayout_11.addWidget(self.MAG_Z_label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.MAG_X_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.MAG_X_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MAG_X_text_label.setObjectName("MAG_X_text_label")
        self.verticalLayout_12.addWidget(self.MAG_X_text_label)
        self.MAG_Y_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.MAG_Y_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MAG_Y_text_label.setObjectName("MAG_Y_text_label")
        self.verticalLayout_12.addWidget(self.MAG_Y_text_label)
        self.MAG_Z_text_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.MAG_Z_text_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MAG_Z_text_label.setObjectName("MAG_Z_text_label")
        self.verticalLayout_12.addWidget(self.MAG_Z_text_label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.MAG_X_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.MAG_X_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MAG_X_Unit_label.setObjectName("MAG_X_Unit_label")
        self.verticalLayout_13.addWidget(self.MAG_X_Unit_label)
        self.MAG_Y_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.MAG_Y_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MAG_Y_Unit_label.setObjectName("MAG_Y_Unit_label")
        self.verticalLayout_13.addWidget(self.MAG_Y_Unit_label)
        self.MAG_Z_Unit_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.MAG_Z_Unit_label.setAlignment(QtCore.Qt.AlignCenter)
        self.MAG_Z_Unit_label.setObjectName("MAG_Z_Unit_label")
        self.verticalLayout_13.addWidget(self.MAG_Z_Unit_label)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.MAG_label = QtWidgets.QLabel(self.MAG_tab)
        self.MAG_label.setGeometry(QtCore.QRect(10, 0, 141, 31))
        self.MAG_label.setObjectName("MAG_label")
        self.Sensor_tabWidget.addTab(self.MAG_tab, "")
        self.rotate_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.rotate_pushButton.setEnabled(True)
        self.rotate_pushButton.setGeometry(QtCore.QRect(868, 430, 141, 21))
        self.rotate_pushButton.setObjectName("rotate_pushButton")
        self.core_status_label = QtWidgets.QLabel(self.centralwidget)
        self.core_status_label.setGeometry(QtCore.QRect(660, 360, 191, 31))
        self.core_status_label.setObjectName("core_status_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen_Directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_Directory.setEnabled(False)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate_Timelapse = QtWidgets.QAction(MainWindow)
        self.actionCreate_Timelapse.setObjectName("actionCreate_Timelapse")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.Expert_tab.setCurrentIndex(1)
        self.frameMS_comboBox.setCurrentIndex(7)
        self.coreMS_comboBox.setCurrentIndex(7)
        self.Sensor_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FlashLapse Commad Point"))
        self.Address_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">LED Address</span></p></body></html>"))
        self.color_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Color Setting</span></p></body></html>"))
        self.Start_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Start LED:</span></p></body></html>"))
        self.Start_label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">End LED:</span></p></body></html>"))
        self.BRT_lable.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Brightness:</span></p></body></html>"))
        self.W_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">White:</span></p></body></html>"))
        self.light_Reset_pushButton.setText(_translate("MainWindow", "RESET"))
        self.light_Confirm_pushButton.setText(_translate("MainWindow", "CONFIRM"))
        self.G_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Green:</span></p></body></html>"))
        self.R_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Red:</span></p></body></html>"))
        self.B_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Blue:</span></p></body></html>"))
        self.presets_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Presets</span></p></body></html>"))
        self.rainbow_pushButton.setText(_translate("MainWindow", "Rainbow"))
        self.disco_pushButton.setText(_translate("MainWindow", "Disco"))
        self.lightCycle_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Power Cycle</span></p></body></html>"))
        self.powerCycle_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.Cycle_label.setText(_translate("MainWindow", "Cycle Duration:"))
        self.confirmCycle_pushButton.setText(_translate("MainWindow", "CONFIRM"))
        self.IR_pushButton.setText(_translate("MainWindow", "INFRARED:OFF"))
        self.IR_checkBox.setText(_translate("MainWindow", "IR When Imaging"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Lighting_tab), _translate("MainWindow", "LIGHTING"))
        self.frame_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">FRAME</span></p></body></html>"))
        self.core_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">CORE</span></p></body></html>"))
        self.frameErgz_pushButton.setText(_translate("MainWindow", "ENERGIZE COILS"))
        self.frame_spinBox.setSuffix(_translate("MainWindow", " RPM"))
        self.core_spinBox.setSuffix(_translate("MainWindow", " RPM"))
        self.coreErgz_pushButton.setText(_translate("MainWindow", "ENERGIZE COILS"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Frame_tab), _translate("MainWindow", "MOTION"))
        self.Image_Title.setText(_translate("MainWindow", "Image Sequence Title"))
        self.addDate_pushButton.setText(_translate("MainWindow", "Add Date"))
        self.Image_Interval.setText(_translate("MainWindow", "Image Capture Interval"))
        self.ICI_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.Image_Duration.setText(_translate("MainWindow", "Image Sequence Duration"))
        self.ISD_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.directory_label.setText(_translate("MainWindow", "Sequence Title Required"))
        self.directory_pushButton.setText(_translate("MainWindow", "Select Storage Directory"))
        self.Progress_Label.setText(_translate("MainWindow", "Progress: 0 / 1"))
        self.resolution_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">IMAGING RESOLUTION</span></p></body></html>"))
        self.JPG_radioButton.setText(_translate("MainWindow", ".JPG"))
        self.PNG_radioButton.setText(_translate("MainWindow", ".PNG"))
        self.resolution_label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">IMAGE FORMAT</span></p></body></html>"))
        self.CoreCtr_label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">X</p></body></html>"))
        self.x_resolution_spinBox.setSuffix(_translate("MainWindow", " px"))
        self.y_resolution_spinBox.setSuffix(_translate("MainWindow", " px"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#000000;\">[ 50 , 3240 ]</span></p></body></html>"))
        self.CoreCtr_label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#000000;\">[ 50 , 2464 ]</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Imaging_tab), _translate("MainWindow", "IMAGING"))
        self.frameCD_spinBox.setSuffix(_translate("MainWindow", " mA"))
        self.frameCD_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Current Offset:</p></body></html>"))
        self.framePW_spinBox.setSuffix(_translate("MainWindow", " ms"))
        self.framePI_spinBox.setSuffix(_translate("MainWindow", " ms"))
        self.framePW_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Pulse Width:</p></body></html>"))
        self.framePI_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Pulse Interval:</p></body></html>"))
        self.frameEC_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Expert Controls</span></p></body></html>"))
        self.frameMS_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Microstepping:</p></body></html>"))
        self.frameApply_pushButton.setText(_translate("MainWindow", "APPLY"))
        self.frameMS_comboBox.setCurrentText(_translate("MainWindow", "128"))
        self.frameMS_comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.frameMS_comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.frameMS_comboBox.setItemText(2, _translate("MainWindow", "4"))
        self.frameMS_comboBox.setItemText(3, _translate("MainWindow", "8"))
        self.frameMS_comboBox.setItemText(4, _translate("MainWindow", "16"))
        self.frameMS_comboBox.setItemText(5, _translate("MainWindow", "32"))
        self.frameMS_comboBox.setItemText(6, _translate("MainWindow", "64"))
        self.frameMS_comboBox.setItemText(7, _translate("MainWindow", "128"))
        self.frameReset_pushButton.setText(_translate("MainWindow", "RESET"))
        self.Expert_tab.setTabText(self.Expert_tab.indexOf(self.tab), _translate("MainWindow", "Frame"))
        self.coreCD_spinBox.setSuffix(_translate("MainWindow", " mA"))
        self.coreCD_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Current Offset:</p></body></html>"))
        self.corePW_spinBox.setSuffix(_translate("MainWindow", " ms"))
        self.corePI_spinBox.setSuffix(_translate("MainWindow", " ms"))
        self.corePW_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Pulse Width:</p></body></html>"))
        self.corePI_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Pulse Interval:</p></body></html>"))
        self.coreEC_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Expert Controls</span></p></body></html>"))
        self.coreMS_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Microstepping:</p></body></html>"))
        self.coreApply_pushButton.setText(_translate("MainWindow", "APPLY"))
        self.coreMS_comboBox.setCurrentText(_translate("MainWindow", "128"))
        self.coreMS_comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.coreMS_comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.coreMS_comboBox.setItemText(2, _translate("MainWindow", "4"))
        self.coreMS_comboBox.setItemText(3, _translate("MainWindow", "8"))
        self.coreMS_comboBox.setItemText(4, _translate("MainWindow", "16"))
        self.coreMS_comboBox.setItemText(5, _translate("MainWindow", "32"))
        self.coreMS_comboBox.setItemText(6, _translate("MainWindow", "64"))
        self.coreMS_comboBox.setItemText(7, _translate("MainWindow", "128"))
        self.frameReset_pushButton_2.setText(_translate("MainWindow", "RESET"))
        self.Expert_tab.setTabText(self.Expert_tab.indexOf(self.tab_2), _translate("MainWindow", "Core"))
        self.label.setText(_translate("MainWindow", "~"))
        self.label_4.setText(_translate("MainWindow", "~"))
        self.label_5.setText(_translate("MainWindow", "~"))
        self.label_6.setText(_translate("MainWindow", "~"))
        self.frameCI_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Frame Code Injection</span></p></body></html>"))
        self.frameCI_pushButton.setText(_translate("MainWindow", "INJECT"))
        self.label_13.setText(_translate("MainWindow", "~"))
        self.label_14.setText(_translate("MainWindow", "~"))
        self.label_15.setText(_translate("MainWindow", "~"))
        self.label_16.setText(_translate("MainWindow", "~"))
        self.coreCI_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Core Code Injection</span></p></body></html>"))
        self.coreCI_pushButton.setText(_translate("MainWindow", "INJECT"))
        self.label_17.setText(_translate("MainWindow", "~"))
        self.label_18.setText(_translate("MainWindow", "~"))
        self.label_19.setText(_translate("MainWindow", "~"))
        self.label_20.setText(_translate("MainWindow", "~"))
        self.lightingCI_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Lighting Code Injection</span></p></body></html>"))
        self.lightingCI_pushButton.setText(_translate("MainWindow", "INJECT"))
        self.label_21.setText(_translate("MainWindow", "~"))
        self.label_22.setText(_translate("MainWindow", "~"))
        self.label_23.setText(_translate("MainWindow", "~"))
        self.label_24.setText(_translate("MainWindow", "~"))
        self.imagingCI_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Imaging Core Injection</span></p></body></html>"))
        self.imagingCI_pushButton.setText(_translate("MainWindow", "INJECT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.core_tab), _translate("MainWindow", "ADVANCED"))
        self.startImaging_pushButton.setText(_translate("MainWindow", "START TIMELAPSE"))
        self.snapshot_pushButton.setText(_translate("MainWindow", "SNAPSHOT"))
        self.preview_pushButton.setText(_translate("MainWindow", "PREVIEW"))
        self.version_label.setText(_translate("MainWindow", "Firmware: V 1.03 beta"))
        self.ACC_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Accelerometer</span></p></body></html>"))
        self.ACC_X_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X:</span></p></body></html>"))
        self.ACC_Y_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y:</span></p></body></html>"))
        self.ACC_Z_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Z:</span></p></body></html>"))
        self.ACC_X_text_label.setText(_translate("MainWindow", "offline"))
        self.ACC_Y_text_label.setText(_translate("MainWindow", "offline"))
        self.ACC_Z_text_label.setText(_translate("MainWindow", "offline"))
        self.ACC_X_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">m/s</span><span style=\" font-weight:600; vertical-align:super;\">2</span></p></body></html>"))
        self.ACC_Y_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">m/s</span><span style=\" font-weight:600; vertical-align:super;\">2</span></p></body></html>"))
        self.ACC_Z_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">m/s</span><span style=\" font-weight:600; vertical-align:super;\">2</span></p></body></html>"))
        self.Sensor_tabWidget.setTabText(self.Sensor_tabWidget.indexOf(self.ACC_tab), _translate("MainWindow", "ACC"))
        self.GYRO_X_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X:</span></p></body></html>"))
        self.GYRO_Y_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y:</span></p></body></html>"))
        self.GYRO_Z_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Z:</span></p></body></html>"))
        self.GYRO_X_text_label.setText(_translate("MainWindow", "offline"))
        self.GYRO_Y_text_label.setText(_translate("MainWindow", "offline"))
        self.GYRO_Z_text_label.setText(_translate("MainWindow", "offline"))
        self.GYRO_X_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">deg/s</span></p></body></html>"))
        self.GYRO_Y_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">deg/s</span></p></body></html>"))
        self.GYRO_Z_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">deg/s</span></p></body></html>"))
        self.GYRO_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Gyroscope</span></p></body></html>"))
        self.Sensor_tabWidget.setTabText(self.Sensor_tabWidget.indexOf(self.GYRO_tab), _translate("MainWindow", "GYRO"))
        self.MAG_X_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">X:</span></p></body></html>"))
        self.MAG_Y_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Y:</span></p></body></html>"))
        self.MAG_Z_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Z:</span></p></body></html>"))
        self.MAG_X_text_label.setText(_translate("MainWindow", "offline"))
        self.MAG_Y_text_label.setText(_translate("MainWindow", "offline"))
        self.MAG_Z_text_label.setText(_translate("MainWindow", "offline"))
        self.MAG_X_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">μTesla</span></p></body></html>"))
        self.MAG_Y_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">μTesla</span></p></body></html>"))
        self.MAG_Z_Unit_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">μTesla</span></p></body></html>"))
        self.MAG_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Magnetometer</span></p></body></html>"))
        self.Sensor_tabWidget.setTabText(self.Sensor_tabWidget.indexOf(self.MAG_tab), _translate("MainWindow", "MAG"))
        self.rotate_pushButton.setText(_translate("MainWindow", "ROTATE IMAGE"))
        self.core_status_label.setText(_translate("MainWindow", "Imaging Core Status: IDLE"))
        self.actionOpen_Directory.setText(_translate("MainWindow", "Open Directory"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCreate_Timelapse.setText(_translate("MainWindow", "Create Timelapse"))


